### ISSUE TITLE
1.2版本出问题了

### ISSUE THREAD

**Issue by xxc0916** [luckytianyiyan/A-star#1]
尝试修改，无奈水平太差。初学者还在怕坑中

**Comment by ty0x2333** [comment]
@xxc0916 修改了一下, 在 1.2.0 版本可以跑起来了. 你可以使用master最新的代码, 再尝试一下.

**Comment by ty0x2333** [comment]
fixed https://github.com/luckytianyiyan/A-star/commit/bae18c2fde6d321d1053e26437150819830d7c0b
